### ISSUE TITLE
I am getting this error pls help...

### ISSUE THREAD

**Issue by Suman2023** [Vicradon/shopping-cart-app#2]
NoSuchMethodError:
**Class '_InternalLinkedHashMap<dynamic,dynamic> has no instance method 'call'.
Receiver: _LinkedHashMap
Len 2
Tried calling: call("cart items"**)

**Comment by vicradon** [comment]
I need a better understanding of the issue.

Did you clone the repo and run into this?

**Comment by Suman2023** [comment]
It is solved.. thnx for the code.. and getting in touch!

**Comment by vicradon** [comment]
You're welcome
