### ISSUE TITLE
mapping 

### ISSUE THREAD

**Issue by anasnaji25** [Vicradon/shopping-cart-app#4]
can i map my firebase data to the [shop items] ....how can i map to it....please give the correct syntax

**Comment by vicradon** [comment]
Hello
You're meant to make an API request to your firestore API to get the data.
Also, anytime you make a change, you're meant to update firestore with the
new data.

**Comment by anasnaji25** [comment]
thanks for your responds ...these codes works very well. I just want your help.how can i persist those cart products. i don't want to lose the products in the cart while the user log out from the app . how is it possible .i want to store that cart products in the user storage(in the device like Cache), i don't want to persist the cart products i the firestore it will increase the chance of reads, iam new to flutter. kindly help me with this

**Comment by vicradon** [comment]
So here's the thing

You can save the data locally on the device using sqflite. It is a Flutter
package available on pub.dev https://pub.dev/packages/sqflite

You should take this tutorial https://youtu.be/E4yRzqChFxY to get a hang of
it

I hope this helps.

**Comment by anasnaji25** [comment]
Thanks
